version: '2.0.{build}-alpha'
image: Visual Studio 2017
branches:
  only:
  - master
clone_depth: 1
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/ClacksMiddleware.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp2.0/publish
  - cmd: dotnet publish --configuration Production ./src/ClacksMiddleware.csproj
  # Create a NuGet packge for uploading
  - cmd: dotnet pack ./src/ClacksMiddleware.csproj --configuration Production --output nupkgs
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\nupkgs\ClacksMiddlware.*.nupkg'
   name: NugetPackage
   type: Auto
test_script:
  # tests in here
  - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  - cmd: cd tests
  - cmd: dotnet test
  - cmd: cd ..
deploy:
 provider: Environment
 name: NuGet-90Days
on_finish :
  # any cleanup in here